### PR TITLE
Tiny changes

### PR DESCRIPTION
**Pull request by katsel**
- Added `.rebar/` to `.gitignore`
- test README: format code
- Running the tests for the first time, it wasn't clear to me what "top level directory" was refering to. Turns out it's refering to the Mango directory (not CouchDB), so I wrote that down.

### CODE REVIEW

**Comment by janl** [comment]
+1

**Comment by nickva** [comment]
+1

**Comment by nickva** [comment]
Rebased and merged.

Thanks @katsel and @janl !

**Comment by nickva** [comment]
@katsel since I rebased on latest the pr didn't automatically move to 'merged' state. Would you mind closing it by hand.

Thank you

**Pull request closed without merging**
