### PR TITLE
Configurable default limit

### PR DESCRIPTION
**Pull request by rnewson**

### CODE REVIEW

**Comment by kxepal** [comment]
+1
Thought should note that this changes default behaviour for some indexers which can surprise people.

**Comment by tonysun83** [comment]
This ties in with https://github.com/apache/couchdb-couch-mrview/pull/56. Can we discuss a little more with making limits configurable across the board?

**Comment by kxepal** [comment]
@tonysun83 
I see in this PR unification of all the limits, but agree.

**Comment by tonysun83** [comment]
The question arises: do we want to see json indexes as an extension of views and thus use the same limits or as a separate entity itself and thus a separate configurable value? I'll update the other PR as well regarding configuring view limits once I collect my thoughts.

**Comment by kxepal** [comment]
@tonysun83 Good point. I think, from user side, it would be hard to explain why views and mango indexes should act differently.

**Comment by tonysun83** [comment]
+1, let's merge this and then open a PR later to match mango and views

**Comment by davisp** [comment]
+1

**Pull request merged**
