### PR TITLE
Fix crypto deprecations

### PR DESCRIPTION
**Pull request by rnewson**
COUCHDB-2825

### CODE REVIEW

**Comment by tonysun83** [comment]
All the mango tests are failing here, but I'm assuming it's due to https://github.com/apache/couchdb-mango/pull/18 and not related to this crypto change.

**Comment by kxepal** [comment]
@tonysun83 failure is ok here. We cannot handle PRs that affects multiple repositories with travis. To make them green here, need to merge https://github.com/apache/couchdb-couch/pull/103 first.

**Comment by tonysun83** [comment]
@kxepal: oh, didn't realize couch_crypto is not merged yet. In situations like these, where one PR is dependent on another PR, what's the issue process? Wait for first PR to be merged or give a +1 on faith?

**Comment by kxepal** [comment]
Well, if it's possible: merge main PR and then check for others. But most of time it's not possible due to cross-references. So the most solid way is to apply all of them and check them all instantly.

**Pull request merged**
